// Navjot Ahuja - Khat
const LYRICS = [
  { time: "00:20.01", text: "Kaagaz ke phool laau tere liye", en: "I'll bring paper flowers for you" },
  { time: "00:26.61", text: "Khat likhu tere liye", en: "I'll write a letter for you" },
  { time: "00:32.02", text: "Mai Khuda me maanu nahi", en: "I don't believe in God" },
  { time: "00:36.97", text: "Par maangu dua tere liye", en: "But I pray for you" },
  { time: "00:44.14", text: "Tere liye ghar banaau", en: "I'll build a home for you" },
  { time: "00:49.47", text: "Deewaarein neele rang se sajaau", en: "I'll decorate the walls in blue" },
  { time: "00:54.59", text: "Pasand hai tumhe, maloom hai", en: "You know you like it" },
  { time: "01:00.00", text: "Tumne bataya tha ek dafe", en: "You once told me" },
  { time: "01:05.38", text: "Neele phool laau tere liye", en: "I'll bring blue flowers for you" },
  { time: "01:12.05", text: "Khat likhu tere liye", en: "I'll write a letter for you" },
  { time: "01:17.50", text: "Mai Khuda me maanu nahi", en: "I don't believe in God" },
  { time: "01:22.48", text: "Par maangu dua tere liye", en: "But I pray for you" },
  { time: "01:48.88", text: "Teri baatein nasamajh si phir bhi jaayaz lag rahi hain", en: "Your words feel so senseless, yet they feel right" },
  { time: "01:59.42", text: "Tu pareshan kar rahi hai phir bhi masoom lag rahi hai", en: "You drive me crazy, yet you look so innocent" },
  { time: "02:09.48", text: "Tere liye mandir jaaun", en: "I'll go to the temple for you" },
  { time: "02:14.82", text: "Tere naam ka diya jalaaun", en: "I'll light a lamp in your name" },
  { time: "02:19.98", text: "Hasta rahe tu chaahe jo ho", en: "May you keep smiling, no matter what" },
  { time: "02:25.47", text: "Teri hasi ko nazar na lage", en: "May no evil eye touch your smile" },
  { time: "02:30.81", text: "Kaagaz ke phool laau tere liye", en: "I'll bring paper flowers for you" },
  { time: "02:37.37", text: "Khat likhu tere liye", en: "I'll write a letter for you" },
  { time: "02:42.79", text: "Mai Khuda me maanu nahi", en: "I don't believe in God" },
  { time: "02:47.68", text: "Par maangu dua tere liye", en: "But I pray for you" },
  { time: "03:34.84", text: "Tere liye hum bane hain", en: "I am made for you" },
  { time: "03:40.20", text: "Tere liye badal rahe hain", en: "I'm changing for you" },
  { time: "03:45.50", text: "Kya mohabbat ho gayi hai", en: "Has love happened?" },
  { time: "03:50.88", text: "Teri hi teri baatein kare", en: "I only talk about you" },
  { time: "03:56.19", text: "Tere liye ghar banaau", en: "I'll build a home for you" },
  { time: "04:01.51", text: "Deewaarein neele rang se sajaau", en: "I'll decorate the walls in blue" },
  { time: "04:06.67", text: "Pasand hai tumhe, maloom hai", en: "You know you like it" },
  { time: "04:12.19", text: "Tumne bataya tha ek dafe", en: "You once told me" },
  { time: "04:25.45", text: "Dekh shayar bana tere liye", en: "See, I've become a poet for you" },
  { time: "04:31.93", text: "Nagma likha tere liye", en: "I wrote a song for you" },
  { time: "04:37.57", text: "Mai Khuda me maanu kyun", en: "Why should I believe in God?" },
  { time: "04:42.78", text: "Tu Khuda mere liye", en: "You are my God" }
];